services:
  petlocation:
    build: .
    container_name: petlocation_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - POSITIONSTACK_API_KEY=d1adb09ff77826f82d0be6a73d6256fb
    depends_on:
      - prometheus
    network_mode: "host"


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    network_mode: "host"



